/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { LineEntry, UserProfile } from '../types';
import {
  calculateLineMetrics,
  calculateFactoryOverall,
  calculateStyleSummary,
  formatDateLabel
} from '../utils';

export interface PDFReportOptions {
  includeFloors?: boolean;
  includeStyles?: boolean;
  includeLineMatrix?: boolean;
  includeSignatures?: boolean;
  orientation?: 'portrait' | 'landscape';
}

export interface GeneratePDFParams {
  lines: LineEntry[];
  reportDate: string;
  profile?: UserProfile;
  options?: PDFReportOptions;
}

/**
 * Builds a professional, multi-section summarized PDF document for
 * daily line performance on the selected date.
 */
export function generateDailyPerformancePDF({
  lines,
  reportDate,
  profile,
  options = {}
}: GeneratePDFParams): jsPDF {
  const {
    includeFloors = true,
    includeStyles = true,
    includeLineMatrix = true,
    includeSignatures = true,
    orientation = 'landscape'
  } = options;

  // Filter lines for the selected report date
  const dayLines = lines.filter(l => l.date === reportDate);
  const activeLines = dayLines.length > 0 ? dayLines : lines;

  // Compute overall factory metrics
  const factory = calculateFactoryOverall(activeLines);
  const formattedDate = formatDateLabel(reportDate);

  // Initialize jsPDF document
  const doc = new jsPDF({
    orientation: orientation,
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 12;

  // Color palette
  const primaryTeal: [number, number, number] = [23, 111, 120]; // #176f78
  const darkTeal: [number, number, number] = [23, 52, 58]; // #17343a
  const softBg: [number, number, number] = [241, 238, 230]; // #f1eee6
  const textDark: [number, number, number] = [30, 41, 59]; // slate-800
  const textMuted: [number, number, number] = [82, 112, 120]; // #527078

  // Helper for drawing header bar
  const drawHeader = () => {
    // Top banner
    doc.setFillColor(darkTeal[0], darkTeal[1], darkTeal[2]);
    doc.rect(0, 0, pageWidth, 24, 'F');

    // Accent line
    doc.setFillColor(primaryTeal[0], primaryTeal[1], primaryTeal[2]);
    doc.rect(0, 24, pageWidth, 2, 'F');

    // Company & Document Title
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(14);
    doc.text('DEBONAIR GROUP • UNIT-02 GARMENTS LTD.', margin, 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text('INDUSTRIAL ENGINEERING & PRODUCTION CONTROL DEPARTMENT', margin, 16);
    doc.text('EXECUTIVE DAILY LINE PERFORMANCE & TELEMETRY AUDIT REPORT', margin, 21);

    // Date & Shift info on right
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text(`REPORT DATE: ${reportDate.toUpperCase()}`, pageWidth - margin, 10, { align: 'right' });

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8.5);
    doc.text(`Calendar: ${formattedDate}`, pageWidth - margin, 15, { align: 'right' });
    const engineer = profile?.name ? `${profile.name} (${profile.role})` : 'Industrial Engineer';
    doc.text(`Generated By: ${engineer}`, pageWidth - margin, 20, { align: 'right' });
  };

  drawHeader();

  let currentY = 32;

  // -------------------------------------------------------------
  // 1. EXECUTIVE SUMMARY KPI CARDS / TABLE
  // -------------------------------------------------------------
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.setTextColor(darkTeal[0], darkTeal[1], darkTeal[2]);
  doc.text('1. EXECUTIVE SUMMARY & SHOP FLOOR TOTALS', margin, currentY);

  currentY += 4;

  const totalLinesRunning = activeLines.length;
  const varianceSign = factory.targetVariance >= 0 ? `+${factory.targetVariance.toLocaleString()}` : factory.targetVariance.toLocaleString();
  const efficiencyColor = factory.overallEfficiency >= 80 ? 'Optimal' : factory.overallEfficiency >= 65 ? 'Acceptable' : 'Under Target';
  const producedHrs = (factory.totalProducedMinutes / 60).toFixed(1);
  const availableHrs = (factory.totalAvailableMinutes / 60).toFixed(1);

  const kpiData = [
    [
      'Active Sewing Lines',
      'Target Production',
      'Achieved Output',
      'Target Variance',
      'Factory Efficiency',
      'Present Manpower',
      'Absent Manpower',
      'Attendance Rate',
      'In-Line Total WIP',
      'Std Produced Hours'
    ],
    [
      `${totalLinesRunning} Lines`,
      `${factory.totalTargetProd.toLocaleString()} pcs`,
      `${factory.totalAchievedProd.toLocaleString()} pcs`,
      `${varianceSign} pcs`,
      `${factory.overallEfficiency}% (${efficiencyColor})`,
      `${factory.totalPresent} Ops/Hlp`,
      `${factory.totalAbsent} Workers`,
      `${factory.attendanceRate}%`,
      `${factory.totalWip.toLocaleString()} pcs`,
      `${producedHrs} / ${availableHrs} hrs`
    ]
  ];

  autoTable(doc, {
    startY: currentY,
    head: [kpiData[0]],
    body: [kpiData[1]],
    margin: { left: margin, right: margin },
    theme: 'grid',
    headStyles: {
      fillColor: primaryTeal,
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 7.5,
      halign: 'center'
    },
    bodyStyles: {
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'center',
      textColor: textDark,
      fillColor: [250, 249, 246]
    },
    styles: {
      cellPadding: 2,
      lineColor: [217, 210, 194],
      lineWidth: 0.2
    }
  });

  currentY = (doc as any).lastAutoTable.finalY + 7;

  // -------------------------------------------------------------
  // 2. FLOOR-WISE PERFORMANCE SUMMARY TABLE
  // -------------------------------------------------------------
  if (includeFloors) {
    const floorMap = new Map<string, {
      floor: string;
      linesCount: number;
      target: number;
      actual: number;
      present: number;
      absent: number;
      producedMins: number;
      availMins: number;
      wip: number;
    }>();

    activeLines.forEach(l => {
      const metrics = calculateLineMetrics(l);
      const floorKey = l.floor.includes('Floor 01') ? 'Floor 01 (Unit-02)' : l.floor.includes('Floor 02') ? 'Floor 02 (Unit-02)' : l.floor;
      if (!floorMap.has(floorKey)) {
        floorMap.set(floorKey, {
          floor: floorKey,
          linesCount: 1,
          target: l.targetProd,
          actual: l.achievedProd,
          present: metrics.totalPresentMP,
          absent: metrics.totalAbsentMP,
          producedMins: metrics.standardProducedMinutes,
          availMins: metrics.availableMinutes,
          wip: l.wip
        });
      } else {
        const item = floorMap.get(floorKey)!;
        item.linesCount += 1;
        item.target += l.targetProd;
        item.actual += l.achievedProd;
        item.present += metrics.totalPresentMP;
        item.absent += metrics.totalAbsentMP;
        item.producedMins += metrics.standardProducedMinutes;
        item.availMins += metrics.availableMinutes;
        item.wip += l.wip;
      }
    });

    const floorRows = Array.from(floorMap.values()).map(f => {
      const eff = f.availMins > 0 ? (f.producedMins / f.availMins) * 100 : 0;
      const att = f.present + f.absent > 0 ? (f.present / (f.present + f.absent)) * 100 : 100;
      const variance = f.actual - f.target;
      return [
        f.floor,
        `${f.linesCount} Lines`,
        f.target.toLocaleString(),
        f.actual.toLocaleString(),
        variance >= 0 ? `+${variance.toLocaleString()}` : `${variance.toLocaleString()}`,
        `${eff.toFixed(1)}%`,
        `${f.present} / ${f.absent}`,
        `${att.toFixed(1)}%`,
        f.wip.toLocaleString()
      ];
    });

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(darkTeal[0], darkTeal[1], darkTeal[2]);
    doc.text('2. FLOOR & PRODUCTION UNIT SUMMARY', margin, currentY);

    currentY += 3;

    autoTable(doc, {
      startY: currentY,
      head: [['Floor / Unit', 'Lines', 'Target (pcs)', 'Actual (pcs)', 'Variance', 'Efficiency %', 'MP (Pres/Abs)', 'Attendance %', 'Total WIP']],
      body: floorRows,
      margin: { left: margin, right: margin },
      theme: 'striped',
      headStyles: {
        fillColor: [37, 99, 107],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 7.5
      },
      bodyStyles: {
        fontSize: 7.5,
        textColor: textDark
      },
      columnStyles: {
        0: { fontStyle: 'bold' },
        4: { halign: 'right' },
        5: { halign: 'center', fontStyle: 'bold' },
        7: { halign: 'center' }
      },
      styles: {
        cellPadding: 1.8,
        lineColor: [217, 210, 194],
        lineWidth: 0.15
      }
    });

    currentY = (doc as any).lastAutoTable.finalY + 6;
  }

  // -------------------------------------------------------------
  // 3. STYLE & BUYER SUMMARY TABLE
  // -------------------------------------------------------------
  if (includeStyles) {
    const styleData = calculateStyleSummary(activeLines);
    const styleRows = styleData.map(s => {
      const variance = s.totalAchievedProd - s.totalTargetProd;
      return [
        s.buyer,
        s.style,
        s.avgSmv > 0 ? s.avgSmv.toFixed(2) : '-',
        `${s.lineNumbers.length}`,
        s.totalTargetProd.toLocaleString(),
        s.totalAchievedProd.toLocaleString(),
        variance >= 0 ? `+${variance.toLocaleString()}` : `${variance.toLocaleString()}`,
        `${s.avgEfficiencyPct.toFixed(1)}%`,
        s.totalWip.toLocaleString()
      ];
    });

    // Check if we need a new page for styles
    if (currentY > pageHeight - 45) {
      doc.addPage();
      drawHeader();
      currentY = 32;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(darkTeal[0], darkTeal[1], darkTeal[2]);
    doc.text('3. STYLE & BUYER PRODUCTION ROLLUP', margin, currentY);

    currentY += 3;

    autoTable(doc, {
      startY: currentY,
      head: [['Buyer', 'Style Specification', 'SMV', 'Lines', 'Target (pcs)', 'Actual (pcs)', 'Variance', 'Efficiency %', 'In-Line WIP']],
      body: styleRows,
      margin: { left: margin, right: margin },
      theme: 'striped',
      headStyles: {
        fillColor: [37, 99, 107],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 7.5
      },
      bodyStyles: {
        fontSize: 7.2,
        textColor: textDark
      },
      columnStyles: {
        0: { fontStyle: 'bold' },
        6: { halign: 'right' },
        7: { halign: 'center', fontStyle: 'bold' }
      },
      styles: {
        cellPadding: 1.8,
        lineColor: [217, 210, 194],
        lineWidth: 0.15
      }
    });

    currentY = (doc as any).lastAutoTable.finalY + 6;
  }

  // -------------------------------------------------------------
  // 4. DETAILED LINE-BY-LINE DAILY PERFORMANCE MATRIX
  // -------------------------------------------------------------
  if (includeLineMatrix) {
    if (currentY > pageHeight - 55) {
      doc.addPage();
      drawHeader();
      currentY = 32;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.setTextColor(darkTeal[0], darkTeal[1], darkTeal[2]);
    doc.text('4. DETAILED LINE-BY-LINE PERFORMANCE & TELEMETRY MATRIX', margin, currentY);

    currentY += 3;

    const lineRows = activeLines.map(line => {
      const metrics = calculateLineMetrics(line);
      const variance = line.achievedProd - line.targetProd;
      const cleanFloor = line.floor.replace('Floor 0', 'F-').replace(' Floor', '');
      const bottleneckInfo = line.bottleneck?.station
        ? `${line.bottleneck.station} (${line.bottleneck.cycleTime}s/${line.bottleneck.targetCT}s)`
        : 'None';

      return [
        `L-${line.lineNo}`,
        cleanFloor,
        line.buyer,
        line.style.length > 20 ? line.style.slice(0, 19) + '…' : line.style,
        line.smv > 0 ? line.smv.toFixed(2) : '-',
        `${metrics.totalPresentMP}/${metrics.totalAbsentMP}`,
        line.targetProd.toLocaleString(),
        line.achievedProd.toLocaleString(),
        variance >= 0 ? `+${variance}` : `${variance}`,
        `${metrics.efficiencyPct.toFixed(1)}%`,
        line.wip.toLocaleString(),
        bottleneckInfo,
        line.remarks || 'Standard run'
      ];
    });

    autoTable(doc, {
      startY: currentY,
      head: [
        [
          'Line',
          'Floor',
          'Buyer',
          'Style',
          'SMV',
          'Pres/Abs',
          'Target',
          'Actual',
          'Var',
          'Eff %',
          'WIP',
          'Bottleneck Station',
          'IE Remarks / Actions'
        ]
      ],
      body: lineRows,
      margin: { left: margin, right: margin },
      theme: 'grid',
      headStyles: {
        fillColor: primaryTeal,
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 7
      },
      bodyStyles: {
        fontSize: 6.8,
        textColor: textDark
      },
      columnStyles: {
        0: { fontStyle: 'bold', halign: 'center' },
        4: { halign: 'right' },
        5: { halign: 'center' },
        6: { halign: 'right' },
        7: { halign: 'right' },
        8: { halign: 'right', fontStyle: 'bold' },
        9: { halign: 'center', fontStyle: 'bold' },
        10: { halign: 'right' }
      },
      styles: {
        cellPadding: 1.5,
        lineColor: [217, 210, 194],
        lineWidth: 0.15
      }
    });

    currentY = (doc as any).lastAutoTable.finalY + 6;
  }

  // -------------------------------------------------------------
  // 5. FORMAL IE & PRODUCTION SIGN-OFF SECTION
  // -------------------------------------------------------------
  if (includeSignatures) {
    if (currentY > pageHeight - 32) {
      doc.addPage();
      drawHeader();
      currentY = 32;
    }

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(darkTeal[0], darkTeal[1], darkTeal[2]);
    doc.text('5. VERIFICATION & EXECUTIVE APPROVAL SIGN-OFF', margin, currentY);

    currentY += 4;

    const signatureBlockWidth = (pageWidth - margin * 2 - 20) / 3;
    const signY = currentY + 12;

    const signatures = [
      { role: 'Prepared By: Line Industrial Engineer', sub: profile?.name || 'Line IE Lead' },
      { role: 'Verified By: IE Floor Incharge', sub: 'Floor Operations & Method Study' },
      { role: 'Approved By: Factory General Manager / IE Head', sub: 'Executive Production Control' }
    ];

    signatures.forEach((sig, index) => {
      const startX = margin + index * (signatureBlockWidth + 10);

      // Line
      doc.setDrawColor(180, 180, 180);
      doc.setLineWidth(0.4);
      doc.line(startX, signY, startX + signatureBlockWidth, signY);

      // Role
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(7.5);
      doc.setTextColor(textDark[0], textDark[1], textDark[2]);
      doc.text(sig.role, startX, signY + 4);

      // Subtitle & Date
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(6.5);
      doc.setTextColor(textMuted[0], textMuted[1], textMuted[2]);
      doc.text(`${sig.sub} • Date: ___/___/2026`, startX, signY + 8);
    });
  }

  // -------------------------------------------------------------
  // Page Numbers and Footer Disclaimer
  // -------------------------------------------------------------
  const totalPages = (doc.internal as any).getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(7);
    doc.setTextColor(130, 140, 150);

    // Footer line
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, pageHeight - 7, pageWidth - margin, pageHeight - 7);

    doc.text(
      `Debonair Unit-02 Garments Ltd. • Official IE Line Performance Report • Shift Date: ${reportDate}`,
      margin,
      pageHeight - 3.5
    );
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 3.5, { align: 'right' });
  }

  return doc;
}

/**
 * Convenience method to trigger direct browser download of the PDF.
 */
export function downloadDailyPerformancePDF(params: GeneratePDFParams): void {
  const doc = generateDailyPerformancePDF(params);
  const fileName = `Daily_Line_Performance_Report_${params.reportDate}.pdf`;
  doc.save(fileName);
}

/**
 * Generates an in-memory blob URL for previewing or embedding in iframe.
 */
export function getDailyPerformancePDFBlobUrl(params: GeneratePDFParams): string {
  const doc = generateDailyPerformancePDF(params);
  const blob = doc.output('blob');
  return URL.createObjectURL(blob);
}
